language: python
python:
- '2.7'
before_install:
- sudo apt-get update
- sudo apt-get install xvfb
install:
- pip install --upgrade pip
- pip install cython==0.21.2
- pip install -r requirements.txt
script:
- xvfb-run -s "+extension GLX" shovel test
deploy:
  provider: pypi
  user:
    secure: DWfHJo5qhLT7qFlsXlvLA8vbfe5KYSmEcabUiDNzzsCgWfJIpWgXLH5CdqBA4QyqhnbLq40gedg0CLiWCNGlUrMdxonslQdLVBw/n5ndX2zQ12VjF32QAjPIbrDjy50I92arqqKs8wOxQLkfWjq7/a3kw6bLxgMKc1wIN+x2HGw=
  password:
    secure: a9IvePk9W7Skm9CIoeSOCxWy4xSsGj5llmkubrwh1QQp8QTsSdYmNXaplfJqKGWJSxCcKsdhX12F4j0bEvpElyNgPT7y8R3lc63gjf6N7HeEOwJi6Mm3MBh4cN44hU6haDQKc6ogSK5rBbCxHzZvOK6s3kYhiEUAixm/zFPekoA=
  on:
    tags: true
    repo: garyjohnson/kvaut
