language: python
python:
- '2.7'
before_install:
- sudo apt-get update
- sudo apt-get install xvfb
install:
- pip install --upgrade pip
- pip install cython==0.21.2
- pip install kivy
- pip install -r requirements.txt
script:
- xvfb-run -s "+extension GLX" shovel test
deploy:
  provider: pypi
  user: GaryJohnson
  password:
    secure: a3DelI2lvP6PfCrMbeTDFkhwrQpl/EmvuRW/dPlB3Otvt+L2CJ43X1pM8uFgIMlyBbaBKY7fPw3coTZudtLiOGO+8yX6g1vUp+U0PjyUSvO/nGQmh0fjDi8YGCF00LTNJ2r/RwCuk6ENyiUxULQ9J2H2A92mdsNew6oeeIB2m7o=
  on:
    tags: true
    repo: garyjohnson/kvaut
