language: python
python:
- '2.7'
before_install:
- sudo add-apt-repository ppa:kivy-team/kivy -y
- sudo apt-get update
- sudo apt-get install -y build-essential mercurial git python2.7 python-dev ffmpeg libfreetype6-dev libjpeg-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev unzip
- sudo pip install cython==0.21.2
- sudo pip install -U numpy
- hg clone https://bitbucket.org/pygame/pygame
- (cd pygame; python setup.py build; sudo python setup.py install)
- sudo apt-get install -y python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libx11-6 libX11-dev
- sudo apt-get install -y python-setuptools python-opengl gstreamer0.10-plugins-good build-essential libgl1-mesa-dev libgles2-mesa-dev mercurial
- sudo apt-get build-dep -y python-pygame
- sudo apt-get install -y python-pygame
- sudo apt-get install -y python-kivy
- sudo apt-get install -y xvfb
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- xvfb-run -s "+extension GLX" shovel test
deploy:
  provider: pypi
  user: GaryJohnson
  password:
    secure: a3DelI2lvP6PfCrMbeTDFkhwrQpl/EmvuRW/dPlB3Otvt+L2CJ43X1pM8uFgIMlyBbaBKY7fPw3coTZudtLiOGO+8yX6g1vUp+U0PjyUSvO/nGQmh0fjDi8YGCF00LTNJ2r/RwCuk6ENyiUxULQ9J2H2A92mdsNew6oeeIB2m7o=
  on:
    tags: true
    repo: garyjohnson/kvaut
