language: python
python:
- '2.7'
before_install:
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
- sudo apt-add-repository --yes ppa:gstreamer-developers/ppa
- sudo apt-get update

- sudo apt-get install -y build-essential git python2.7 python-dev python-pip python-setuptools
- sudo apt-get install -y libgstreamer1.0-0 libgstreamer1.0-dev libgstreamer1.0-0-dbg gstreamer1.0-plugins-good
- sudo apt-get install -y libsdl2 libsdl2-dev libsdl2-mixer libsdl2-mixer-dev libsdl2-image libsdl2-image-dev libsdl2-net libsdl2-net-dev libsdl2-ttf libsdl2-ttf-dev
- sudo apt-get install -y python-opengl python-enchant mesa-common-dev-lts-quantal libgl1-mesa-dev-lts-quantal libgles2-mesa-dev-lts-quantal libegl1-mesa-dev-lts-quantal libegl1-mesa-drivers-lts-quantal
- sudo pip install cython==0.21.2
- sudo pip install kivy
install:
- sudo pip install -r requirements.txt
script:
- shovel ci_test
deploy:
  provider: pypi
  user: GaryJohnson
  password:
    secure: a3DelI2lvP6PfCrMbeTDFkhwrQpl/EmvuRW/dPlB3Otvt+L2CJ43X1pM8uFgIMlyBbaBKY7fPw3coTZudtLiOGO+8yX6g1vUp+U0PjyUSvO/nGQmh0fjDi8YGCF00LTNJ2r/RwCuk6ENyiUxULQ9J2H2A92mdsNew6oeeIB2m7o=
  on:
    tags: true
    repo: garyjohnson/kvaut
