language: python
python:
- '2.7'
before_install:
- sudo add-apt-repository ppa:kivy-team/kivy -y
- sudo apt-get update
- sudo apt-get install xvfb python3 python3-dev python python-dev python3-deadsnakes python3-kivy-common python3-kivy-bin  python3-pygame python-kivy python3-kivy
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- xvfb-run -s "+extension GLX" shovel test
deploy:
  provider: pypi
  user: GaryJohnson
  password:
    secure: a3DelI2lvP6PfCrMbeTDFkhwrQpl/EmvuRW/dPlB3Otvt+L2CJ43X1pM8uFgIMlyBbaBKY7fPw3coTZudtLiOGO+8yX6g1vUp+U0PjyUSvO/nGQmh0fjDi8YGCF00LTNJ2r/RwCuk6ENyiUxULQ9J2H2A92mdsNew6oeeIB2m7o=
  on:
    tags: true
    repo: garyjohnson/kvaut
